{% set name = "ffnvcodec-headers" %}
{% set version = "10.0.26.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/FFmpeg/nv-codec-headers/releases/download/n{{ version }}/nv-codec-headers-{{ version }}.tar.gz
  sha256: 2552723fef0adbed1c327e9cca167226b35d8a5d17fb86c753b71d70b26f141c

build:
  number: 0
  skip: true  # [osx]
  script: make PREFIX={{ PREFIX }} install

requirements:
  build:
    # git provides the sed command
    - git   # [win]
    - make

test:
  commands:
    - test -f ${PREFIX}/include/ffnvcodec/dynlink_cuda.h       # [unix]
    - test -f ${PREFIX}/include/ffnvcodec/dynlink_cuviddec.h   # [unix]
    - test -f ${PREFIX}/include/ffnvcodec/dynlink_loader.h     # [unix]
    - test -f ${PREFIX}/include/ffnvcodec/dynlink_nvcuvid.h    # [unix]
    - test -f ${PREFIX}/include/ffnvcodec/nvEncodeAPI.h        # [unix]
    - test -f ${PREFIX}/lib/pkgconfig/ffnvcodec.pc             # [unix]

about:
  home: https://git.videolan.org/?p=ffmpeg/nv-codec-headers.gi
  license: MIT
  license_file: LICENSE
  summary: FFmpeg version of headers required to interface with Nvidias codec APIs
  description: |
    FFmpeg version of headers required to interface with Nvidias codec APIs.

    Corresponds to Video Codec SDK version 8.2.25.

    Minimum required driver versions:
    Linux: 396.24 or newer
    Windows: 397.93 or newer

    Optional CUDA 10 features:
    Linux: 410.48 or newer
    Windows: 411.31 or newer

extra:
  recipe-maintainers:
    - hmaarrfk
    - sdvillal
